// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdzdrbcfpiekkerdsfzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkemRyYmNmcGlla2tlcmRzZnpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MDU3OTgsImV4cCI6MjA1Nzk4MTc5OH0.p0tLX_4ngX9olHCsyWdbS7eupjcBhp-bQp6nteq8KEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);